#exception by didviding a number by 0


x=90
y=10



try:
    print(x/y)
except:
    print("oopps divisor is zerro")
else:
    print("there is no exectption")
finally:
    print("i am finally block I execute every time without failll!!!") 


print("this is rest program")